CREATE TABLE public.med_users (
	userid int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	useremail text NOT NULL,
	user_name text NOT null UNIQUE,
	userpassword text NOT NULL,
	CONSTRAINT med_users_pk PRIMARY KEY (userid)
);


CREATE TABLE public.transport_entry (
	transportid int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	starting_location varchar NOT NULL,
	destination_location varchar NOT NULL,
	date_of_transport timestamptz(0) NOT NULL,
	mileage numeric NOT NULL,
	create_date timestamptz(0) NOT NULL DEFAULT now(),
	requested_user int4 NOT NULL
);

-- public.transport_entry foreign keys

ALTER TABLE public.transport_entry ADD CONSTRAINT transport_entry_fk FOREIGN KEY (requested_user) REFERENCES med_users(userid);